
-- buy list tbl ---

CREATE TABLE "PROJECT"."BUY_TBL" 
   (	"BUY_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"BUY_IMG" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"BUY_NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"BUY_COLOR" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"BUY_SIZE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"BUY_PRICE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"BUY_DATE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "BUY_TBL_PK" PRIMARY KEY ("BUY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "BUY_TBL_FK1" FOREIGN KEY ("ID")
	  REFERENCES "PROJECT"."MEMBER_TBL" ("ID") ENABLE
   );