CREATE TABLE "PROJECT"."PRODUCTS_TBL" 
   (	"ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"COLOR" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"SIZE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"IMG" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"MEMBER_ID" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "PRODUCTS_TBL_PK" PRIMARY KEY ("ID"),
     FOREIGN key(MEMBER_ID) references member_tbl (id)
     );